// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/grpc1.proto

package com.ankit.learning.rpc.samples;

public interface FeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:samples.FeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .samples.Feature feature = 1;</code>
   */
  java.util.List<com.ankit.learning.rpc.samples.Feature> 
      getFeatureList();
  /**
   * <code>repeated .samples.Feature feature = 1;</code>
   */
  com.ankit.learning.rpc.samples.Feature getFeature(int index);
  /**
   * <code>repeated .samples.Feature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .samples.Feature feature = 1;</code>
   */
  java.util.List<? extends com.ankit.learning.rpc.samples.FeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .samples.Feature feature = 1;</code>
   */
  com.ankit.learning.rpc.samples.FeatureOrBuilder getFeatureOrBuilder(
      int index);
}
