// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/grpc1.proto

package com.ankit.learning.rpc.samples;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:samples.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The name of the feature.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the feature.
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The point where the feature is detected.
   * </pre>
   *
   * <code>.samples.Point location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <pre>
   * The point where the feature is detected.
   * </pre>
   *
   * <code>.samples.Point location = 2;</code>
   */
  com.ankit.learning.rpc.samples.Point getLocation();
  /**
   * <pre>
   * The point where the feature is detected.
   * </pre>
   *
   * <code>.samples.Point location = 2;</code>
   */
  com.ankit.learning.rpc.samples.PointOrBuilder getLocationOrBuilder();
}
