// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/grpc1.proto

package com.ankit.learning.rpc.samples;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:samples.Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.samples.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.samples.Point lo = 1;</code>
   */
  com.ankit.learning.rpc.samples.Point getLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.samples.Point lo = 1;</code>
   */
  com.ankit.learning.rpc.samples.PointOrBuilder getLoOrBuilder();

  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.samples.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.samples.Point hi = 2;</code>
   */
  com.ankit.learning.rpc.samples.Point getHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.samples.Point hi = 2;</code>
   */
  com.ankit.learning.rpc.samples.PointOrBuilder getHiOrBuilder();
}
